### ISSUE TITLE
Cannot open files transcoded from MP3 to WAV with ffmpeg

### ISSUE THREAD

**Issue by sethhochberg** [teragonaudio/MrsWatson#177]
Hi, 

We're having some problems getting mrswatson to open files which were transcoded from MP3 to WAV using ffmpeg in the following manner: 

`ffmpeg -i input.mp3 output.wav` or even `ffmpeg -i input.mp3 -f wav -acodec pcm_s16le output.wav`

The `file` command identifies files converted in this way as: 
`RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz`

The original source MP3s are identified as follows: 
`MPEG ADTS, layer III, v1, 256 kbps, 44.1 kHz, JntStereo`

These converted files are usable in other media players (VLC, Quicktime, etc) and seem to be valid.

The exact error output from mrswatson is:
`ERROR: Got error message message: WAVE file has invalid data chunk header`

I notice there is another issue open on the project to migrate away from homegrown WAV support - could this be a possible solution? With a few pointers on how to get started, I'm more than happy to see if I can help with that move in this case.
https://github.com/teragonaudio/MrsWatson/issues/142

Error report here:
https://dl.dropboxusercontent.com/u/3030733/mrswatson_error_report.zip

Thanks for any guidance.

**Comment by nikreiman** [comment]
@BasicPro @sethhochberg audiofile support is now in place in master, which should solve this problem. I'm therefore closing this issue, and will start preparing a release. This might take a bit of time, since I still need to fix some Windows-related issues with the libaudiofile-related build. If you would like to test a build for either Linux/Mac, let me know and I can upload a beta somewhere.

Oh yeah, and as an extra bonus, MrsWatson now fully supports AIFF and FLAC files, since this was very easy to do with audiofile. :)

**Comment by digitaltrousers** [comment]
Hi Nik. I haven't been able to compile with audiofile on Windows. Should this be working?
Cheers.
