### ISSUE TITLE
CMake should download third-party libs if not present

### ISSUE THREAD

**Issue by gijzelaerr** [teragonaudio/MrsWatson#198]
```
audiofile sources not found, did you forget to update submodules?
CMake Error at vendor/CMakeLists.txt:58 (message):
  audiofile not found
```

```
FLAC sources not found, did you forget to update submodules?
CMake Error at vendor/CMakeLists.txt:237 (message):
  FLAC not found
```

**Comment by gijzelaerr** [comment]
```
audiofile sources not found, did you forget to update submodules?
CMake Error at vendor/CMakeLists.txt:58 (message):
  audiofile not found
```

```
FLAC sources not found, did you forget to update submodules?
CMake Error at vendor/CMakeLists.txt:237 (message):
  FLAC not found
```

**Comment by nikreiman** [comment]
Yes, the sources are included as a submodule, so just update the submodules
and re-run cmake.

**Comment by gijzelaerr** [comment]
should a release tarball contain the 3rd party libraries? The fetched libraries will always have the same version for a release, so you have a unnecessary dependency on git if you distribute your tarball like this.

**Comment by nikreiman** [comment]
@gijzelaerr Ah, I see, you got the code from the release tarball that GitHub automatically creates. Apparently this is also an unsupported feature:

https://github.com/wbond/package_control/issues/126#issuecomment-5470380

Even though submodules are not perfect in git, I would prefer to use them rather than flattening third-party code into the repo. Copying the sources manually makes it much more difficult to pick up changes from upstream. Also, the libraries are both forked to the @teragonaudio org, since I have pending PRs in both of them which may or may not be merged upstream as well. But this behavior should at least be documented in the README.

Alternately, I guess CMake could download the dependency automatically if the submodule is not found. I can at least re-open this issue and look into that, assuming that it's not too difficult to get working.

**Comment by nikreiman** [comment]
I'm closing this issue for the following reasons:

- I do not want to migrate to git subtree. Even though git submodules have their flaws, they work well, in spite of GitHub's semi-broken zip release feature.
- The third-party libraries are forks, and it is necessary that the zipfile point to a specific SHA1 hash rather than latest master, or else the build will break. AFAIK, it is not possible to tell GitHub to get a zipfile for a specific hash.
- The CMake logic for supporting either submodules or downloaded zipfiles will increase the complexity of the build system.

Sorry to close this issue as "wontfix", however I think that if you want to build from source, git clone is the only way to go.
