### ISSUE TITLE
Clipping, mrs_limiter?

### ISSUE THREAD

**Issue by evandelacruz** [teragonaudio/MrsWatson#253]
Using midi file + vsti.

I have an issue where a fast sequence of loud notes with long sustains causes clipping.  This makes sense, as the new notes basically sum with the already-played notes because of their long sustains. 

In trying to find a solution to this, I came across docs/code/issues related to an internal plugin called mrs_limiter.  I do not have that plugin.  Is it still alive?  Is this the correct approach to deal with this issue?

Since the vsti is generating the audio, I can't limit pre-input.  And since I never know which vsti or preset I will be using, I cannot predictively lower the volume on the vsti parameter.  Limiting post-output is useless of course because the clipping is already present.

I suspect using 32 bit processing would alleviate all of my problems since it likely would have the headroom not to clip.  However, when I use --bit-depth 32 I get a bunch of nasty noise.

Should I / can I use mrs_limiter for this?  How do I use mrs_limiter if it is not in my plugin list?

Does the bit depth setting work on the latest builds? (There is an open issue for bit depth)

The mrs_watson build I am using is Windows 10 compiled on VS2015 compiled on July 16 2016 from the master branch.

Thanks

**Comment by evandelacruz** [comment]
It just occurred to me that if I put a (3rd party) limiter in the chain after the vsti that perhaps mrs watson won't even see the data until post-limiter, and therefore it will not clip.  I am going to give that a try.  Maybe this is a good time to test my Slate vsts with mrs watson.  If I get that working that will be amazing.  I'll update.

**Comment by nikreiman** [comment]
`mrs_limiter` is a built-in brickwall limiter plugin. It is still alive and still built with mw. However, it is not very smart... basically it just caps values to prevent overflow. You will get better sound quality with a proper limiter plugin, but in the worst case, the built-in limiter should at least prevent horrible distortion caused by extreme clipping.

**Comment by nikreiman** [comment]
Also, regarding bit depth, it is not really working as well as I'd like. =/ It's a longstanding issue which requires some rather low-level fixes in the code in order to have it behave properly.

**Comment by evandelacruz** [comment]
The thing is, I believe I am having that horrible distortion caused by extreme clipping.  Is mrs_limiter always "on"?

Also, I guess I should also ask, what the difference is?  If mrs_limiter just hard-caps at 1, isn't that exactly what happens anyways if you sum multiple signals and the result is greater than 1?  Would't the clipping effect be identical with the two methods?  Either way there's a hard-limit.  Unless mrs_limiter is perhaps smarter than you suggest?

**Comment by nikreiman** [comment]
No, `mrs_limiter` is not always on. It must be added to your plugin chain like any other plugin.

As for what happens without a brickwall limiter, that depends on what file format you are exporting to.  Some quick background info here, sorry if this is basic stuff you already know, but I just want to make sure that the technical issue is clear. Internally, all DSP processing by MW and VSTs is done with `double` precision math, so each sample should be in the range of `-1.0` to `1.0`. Of course, a `double` can hold values far outside that range, which isn't really a problem until you want to export the audio to another format.

Most PCM data containers, and specifically, the ones which MW supports, use signed integers instead of floating point math. So a 16-bit WAVE file allows samples to be in the range of `-32767..32767` (ie, a `signed short` in C). So when writing such files, MW must convert the floating point data to integers, which works exactly like you'd suspect... `-1.0` is mapped to `-32767`, and `1.0` to `32767`. The problem is, if a plugin generates data outside of the `-1.0..1.0` range, then it will cause integer overflow when you try to constrain it to a 16-bit `short`.

Since the highest bit of a signed integer is used to represent the sign, `32767` is represented in raw binary as `0111111111111111`, and `-1` is `1000000000000001`. So any number bigger than `32767` ends up being misinterpreted as a *negative* value. This is *much* worse than clipping; it will cause a very audible and nasty click. Hence, MW's limiter just takes every floating value greater than `1.0` and sets it to `1.0` to avoid this. The resulting sound won't be great though, and as you noticed, that can result in clipping, but clipping is better than distortion. It's more of a safety latch than anything else. However, some data containers (like AIFC) support writing floating point data, which means that the sequencer should *not* automatically truncate values outside of this range. That's why `mrs_limiter` exists; it's a safety latch, but it is not always on since that may have bad side effects which negatively impact the sound in some situations.

However, a real limiter should have lookahead and other features designed to soften the clipping so it's not as severe. Here's a quick list of freeware VST limiter plugins that I found:

http://bedroomproducersblog.com/2011/07/24/bpb-freeware-studio-best-free-limiter-vstau-plugins/

Does that answer your question? Or am I way off base here? :)

**Comment by evandelacruz** [comment]
No that was awesome thank you.  Why do negative values have that effect?

**Comment by evandelacruz** [comment]
When I do mrswatson --list-plugins I see two internal plugins, mrs_passthru and mrs_silence.  Should I just assume mrs_limiter is also there?  A safety latch may be all I need honestly.  That nature of my app makes it non-trivial to put a limiter in the chain.  I mean, it's not a huge deal.  I just need to put in logic determining if its a 32 or 64 bit vsti/mrs_watson and then choose a compatible limiter.  I had added maxwell_smart to the chain but it croaked on my 64 bit vstis/mrs_watson.  So, I want to give mrs_limiter a quick try.  I suppose I could just try it.  But ears can lie and my environment isn't very controlled for testing because of the nature of the application.  So i'd rather be 100% sure.

**Comment by nikreiman** [comment]
Regarding negative/positive values, it's not the fact that they are negative that is necessarily bad, it's the sign flipping which causes problems. Imagine a signal which has the following values: `0.99, 1.0, 1.1, 1.0, 0.99`. You can imagine that would be the peak of a nice, gentle wave, right? Nothing super bad there, until we convert those values to 16-bit `shorts`, which yields: `32439, 32767, 36043, 32767, 32439`.

Let's consider a simpler example for a second -- 3-bit numbers. Here we have 2 bits of data and 1 bit for the sign. So the highest positive number that we can store is 3, `011`. `000` and `100` are both 0 (see https://en.wikipedia.org/wiki/Signed_zero). For negative numbers, `101` is -1, `110` is -2, and so on. What happens when we want to store 4? It's just too big to fit in there, so `100` doesn't represent 4, it's -0 instead. So let's consider a similar series of samples as above: `2, 3, 4, 3, 2`. In binary, that would be `010, 011, 100, 011, 010`. But converting that binary data back to real numbers now gives us `2, 3, -0, 3, 2`.

So in the first example of a real-world audio signal, you can see now that when we convert it from float to binary, and back again from binary to float, we don't get `0.99, 1.0, 1.1, 1.0, 0.99` anymore. Instead, that signal will look more like `0.99, 1.0, -1.1, 1.0, 0.99`. Now the signal isn't a nice smooth wave anymore, it has a big jump from 1.0 to -1.1. That will cause a very harsh audible click. I hope that makes sense.

**Comment by nikreiman** [comment]
Also, you're right, `mrs_limiter` wasn't being shown in the list of `--list-plugins`, but it's still there. It just wasn't being shown in the list. I just pushed a commit which fixes that: 290ceb4da7b0915441d8c002955d8dd124de0cd1. Thanks for pointing that out!

**Comment by evandelacruz** [comment]
The explanation makes great sense.  I've been doing this for a long time and I've never understood it all quite as well as I do after reading your explanation.  Spot on... should be quoted in a book.

So I implemented the w1 by George Yohng since there was a 64 and 32 bit version of the dll.  It worked amazingly well.  The clipping is all gone and I believe it also imparted a pleasant tonal change.  Thanks for your help as always.

**Comment by nikreiman** [comment]
I'm glad to hear that you got it working, and that you found a good limiter which sounds great and is without clipping. :)
