### ISSUE TITLE
VST plugin in C

### ISSUE THREAD

**Issue by Alex-Longard** [teragonaudio/MrsWatson#279]
Hello!
Do you can write example for vst plugin in pure C?

**Comment by williamsharkey** [comment]
I too am interested in this topic, however it is very involved.  One must obtain a sdk from steinberg implement the interfaces, and have a compiling toolchain that is compatible. It usually involves a ton of debugging. It was easier when Steinberg distributed the vst2 sdk, but now they are hunting down any copies of it floating around and will only encourage you to make vst3 plugins, which are more complicated. The mess around making a vst has sprung a whole spread of solutions to try deal with the complexity, the most popular being JUCE.  Even teragonaudio had a solution called PluginCore ( https://github.com/teragonaudio/PluginCore ) which is now maintained.

So I recommend that this issue be closed, not because it is not interesting, but it's just too much to cover and off topic for MrsWatson.
